# Generated by Django 3.0.3 on 2020-03-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_discription',
            field=models.TextField(default='This area write image discription'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.FileField(help_text='image should be in a high resolutions Ex. height = 640px & width = 980px', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.FileField(help_text='image should be Height = 480px, Width = 560px', upload_to='images'),
        ),
    ]
