# Generated by Django 3.0.3 on 2020-03-01 11:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0003_auto_20200301_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
        migrations.AddField(
            model_name='post',
            name='post_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This area write image in brief text description'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_short_description',
            field=models.TextField(default='This area write image short description'),
        ),
    ]
