# Generated by Django 3.0.3 on 2020-03-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0004_auto_20200301_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='long_description',
            field=models.TextField(default='this is a dummy text to see users as a long description of the products'),
        ),
        migrations.AddField(
            model_name='header',
            name='short_description',
            field=models.TextField(default='this is a dummy text to see users'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.FileField(help_text='image should be in a high resolutions Ex. height = 640px & width = 720px', upload_to='images'),
        ),
    ]
