# Generated by Django 3.0.3 on 2020-03-02 10:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0005_auto_20200302_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_images',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='header',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='this is a dummy text to see users as a long description of the products'),
        ),
    ]
