# Generated by Django 3.0.3 on 2020-03-03 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0007_auto_20200303_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='image should be Height = 480px, Width = 480px', upload_to='images')),
                ('description', ckeditor.fields.RichTextField(default='about profile details')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='image should be Height = 480px, Width = 480px', upload_to='images')),
                ('description', ckeditor.fields.RichTextField(default='about profile details')),
            ],
        ),
        migrations.CreateModel(
            name='Hvac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='image should be Height = 560px, Width = 480px', upload_to='images')),
                ('description', ckeditor.fields.RichTextField(default='about profile details')),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='image should be Height = 480px, Width = 480px', upload_to='images')),
                ('description', ckeditor.fields.RichTextField(default='about profile details')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='image should be Height = 480px, Width = 480px', upload_to='images')),
                ('description', ckeditor.fields.RichTextField(default='about profile details')),
            ],
        ),
    ]
