# Generated by Django 3.0.3 on 2020-03-03 11:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0008_door_equipment_hvac_metal_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hvac',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metal',
            name='description',
        ),
        migrations.AddField(
            model_name='door',
            name='post_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This area write image in brief text description'),
        ),
        migrations.AddField(
            model_name='door',
            name='post_short_description',
            field=models.TextField(default='This area write image short description'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='post_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This area write image in brief text description'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='post_short_description',
            field=models.TextField(default='This area write image short description'),
        ),
        migrations.AddField(
            model_name='hvac',
            name='post_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This area write image in brief text description'),
        ),
        migrations.AddField(
            model_name='hvac',
            name='post_short_description',
            field=models.TextField(default='This area write image short description'),
        ),
        migrations.AddField(
            model_name='metal',
            name='post_long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This area write image in brief text description'),
        ),
        migrations.AddField(
            model_name='metal',
            name='post_short_description',
            field=models.TextField(default='This area write image short description'),
        ),
    ]
