# Generated by Django 3.0.3 on 2020-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0009_auto_20200303_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='hvac',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
