# Generated by Django 3.0.3 on 2020-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0010_hvac_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
