# Generated by Django 3.0.3 on 2020-03-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellect', '0011_door_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
